# Generated by Django 5.1.3 on 2024-11-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_remove_hotel_image_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact_details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
    ]
